# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='choice_text',
            field=models.CharField(default='Does not Like', max_length=200),
        ),
    ]
