# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0002_song_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='choice_text',
            new_name='choice_set',
        ),
    ]
