# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0003_auto_20160817_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='choice_text',
            new_name='choice_set',
        ),
    ]
