# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0004_auto_20160817_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='choice_set',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_text',
            new_name='song_name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_text',
        ),
        migrations.RemoveField(
            model_name='song',
            name='choice_set',
        ),
        migrations.RemoveField(
            model_name='song',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_genre',
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(to='wavesApp.Genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='playlists',
            field=models.ManyToManyField(to='wavesApp.Playlist'),
        ),
    ]
