# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0004_auto_20160828_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='soundcloud_access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
