# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0005_auto_20160828_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_user_playlist_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_user_private_playlists_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_user_private_tracks_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_user_public_favorites_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_user_track_count',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='soundcloud_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
