# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0005_auto_20160818_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_first_name', models.CharField(max_length=200)),
                ('listener_last_name', models.CharField(max_length=200)),
            ],
        ),
    ]
