# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wavesApp', '0006_auto_20160902_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_user_display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_user_external_urls',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_user_followers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
